document.write("<footer>");
document.write("	<div >");
document.write("		<ul class=\"new\">");
document.write("			<li class=\"style\"><a href =\".\/index.html\" class=\"bar\">Home<\/a><\/li>");
document.write("			<li class=\"style\"><a href =\".\/organizing_committee.html\" class=\"bar\">Organizing Committee<\/a><\/li>");
document.write("			<li class=\"style\"><a href =\".\/program_committee.html\" class=\"bar\">Program Committee<\/a><\/li>");
document.write("			<li class=\"style\"><a href =\".\/important_dates.html\" class=\"bar\">Paper Submission<\/a><\/li>");
document.write("			<li class=\"style\"><a href =\".\/Program.html\" class=\"bar\">Program<\/a><\/li>");
document.write("		<\/ul>");
document.write("		<br><br>");
document.write("	<\/div>");
document.write("<\/footer>");
